// dummyData.js
const ProductData = [
  {
    id: "1",
    title: "Glow & Go Pack",
    price: "₹ 599",
    products: "Facewash, Bleach, Threading",
    about: "Quick glow for party",
  },
  {
    id: "2",
    title: "Glow & Go Pack",
    price: "₹ 1499",
    products: "Facial, Cleanup, Waxing, Threading",
    about: "Perfect bridal glow before your big day",
  },
  {
    id: "3",
    title: "Glow & Go Pack",
    price: "₹ 799",
    products: "Detan, Cleanup, Facewash",
    about: "Stay fresh & tan-free all summer",
  },
  {
    id: "4",
    title: "Glow & Go Pack",
    price: "₹ 1999",
    products: "Spa, Facial, Body Massage",
    about: "Relax & rejuvenate with luxury care",
  },  {
    id: "5",
    title: "Glow & Go Pack",
    price: "₹ 599",
    products: "Facewash, Bleach, Threading",
    about: "Quick glow for party",
  },
  {
    id: "6",
    title: "Glow & Go Pack",
    price: "₹ 1499",
    products: "Facial, Cleanup, Waxing, Threading",
    about: "Perfect bridal glow before your big day",
  },
  {
    id: "7",
    title: "Glow & Go Pack",
    price: "₹ 799",
    products: "Detan, Cleanup, Facewash",
    about: "Stay fresh & tan-free all summer",
  },
  {
    id: "8",
    title: "Glow & Go Pack",
    price: "₹ 1999",
    products: "Spa, Facial, Body Massage",
    about: "Relax & rejuvenate with luxury care",
  },  {
    id: "9",
    title: "Glow & Go Pack",
    price: "₹ 599",
    products: "Facewash, Bleach, Threading",
    about: "Quick glow for party",
  },
  {
    id: "10",
    title: "Glow & Go Pack",
    price: "₹ 1499",
    products: "Facial, Cleanup, Waxing, Threading",
    about: "Perfect bridal glow before your big day",
  },
  {
    id: "11",
    title: "Glow & Go Pack",
    price: "₹ 799",
    products: "Detan, Cleanup, Facewash",
    about: "Stay fresh & tan-free all summer",
  },
  {
    id: "12",
    title: "Glow & Go Pack",
    price: "₹ 1999",
    products: "Spa, Facial, Body Massage",
    about: "Relax & rejuvenate with luxury care",
  },  {
    id: "13",
    title: "Glow & Go Pack",
    price: "₹ 599",
    products: "Facewash, Bleach, Threading",
    about: "Quick glow for party",
  },
  {
    id: "14",
    title: "Glow & Go Pack",
    price: "₹ 1499",
    products: "Facial, Cleanup, Waxing, Threading",
    about: "Perfect bridal glow before your big day",
  },
  {
    id: "15",
    title: "Glow & Go Pack",
    price: "₹ 799",
    products: "Detan, Cleanup, Facewash",
    about: "Stay fresh & tan-free all summer",
  },
  {
    id: "16",
    title: "Glow & Go Pack",
    price: "₹ 1999",
    products: "Spa, Facial, Body Massage",
    about: "Relax & rejuvenate with luxury care",
  },  {
    id: "17",
    title: "Glow & Go Pack",
    price: "₹ 599",
    products: "Facewash, Bleach, Threading",
    about: "Quick glow for party",
  },
  {
    id: "18",
    title: "Glow & Go Pack",
    price: "₹ 1499",
    products: "Facial, Cleanup, Waxing, Threading",
    about: "Perfect bridal glow before your big day",
  },
  {
    id: "19",
    title: "Glow & Go Pack",
    price: "₹ 799",
    products: "Detan, Cleanup, Facewash",
    about: "Stay fresh & tan-free all summer",
  },
  {
    id: "20",
    title: "Glow & Go Pack",
    price: "₹ 1999",
    products: "Spa, Facial, Body Massage",
    about: "Relax & rejuvenate with luxury care",
  },  {
    id: "21",
    title: "Glow & Go Pack",
    price: "₹ 599",
    products: "Facewash, Bleach, Threading",
    about: "Quick glow for party",
  },
  {
    id: "22",
    title: "Glow & Go Pack",
    price: "₹ 1499",
    products: "Facial, Cleanup, Waxing, Threading",
    about: "Perfect bridal glow before your big day",
  },
  {
    id: "23",
    title: "Glow & Go Pack",
    price: "₹ 799",
    products: "Detan, Cleanup, Facewash",
    about: "Stay fresh & tan-free all summer",
  },
  {
    id: "24",
    title: "Glow & Go Pack",
    price: "₹ 1999",
    products: "Spa, Facial, Body Massage",
    about: "Relax & rejuvenate with luxury care",
  },
];

export default ProductData;
